[features]
seeds = false
[programs.devnet]
sol_patreon = "571vwvM69EAqbHbbD1CqeKd5DHr9NsLd2LjbrZAoiYyF"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/thefunnyintrovert/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
